### ISSUE TITLE
Failed to trigger adopt() from pet-shop contract in test.py

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/etch-demos#2] opened 2019-11-19 23:39 UTC
In test.py, I run the following:

`result = api.sync(contract.action(api, 'adopt', fet_tx_fee, [entity1], pet_id))`

But got the following error:

`AttributeError: 'Tree' object has no attribute 'value'`

**Comment by Kevin-Chen0** [comment] 2019-11-20 04:14
See interact-checkpoint.ipynb for reference:

https://github.com/fetchai/etch-demos/blob/master/demos/.ipynb_checkpoints/interact-checkpoint.ipynb

**Comment by wkaluza** [comment] 2019-11-22 14:34
Looks like a Python Etch parser hiccup.

**Comment by NelisDrost** [comment] 2019-11-26 12:24
This was caused by an issue parsing globals with template types, fixed in https://github.com/fetchai/ledger-api-py/pull/66

**Comment by NelisDrost** [comment] 2019-11-26 14:53
The PR above has been merged, and a new version of the api released on PyPi as 0.10.0-alpha6, this issue should now be resolved.

**Comment by Kevin-Chen0** [comment] 2019-12-08 21:47
After using the latest version, this has been resolved. Thank you @NelisDrost.

**Closed as completed** 2019-12-08 21:48 UTC
